# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180104_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='hashed_id',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_id',
        ),
    ]
